#!/usr/bin/env bash
set -e
D="$(cd "$(dirname "$0")" && pwd)"
P="$(pwd)"
echo "==> Copying files ..."
cp "$D/CMakeLists.txt"      "$P/CMakeLists.txt"
cp "$D/dsp_types.hpp"       "$P/include/dsp_types.hpp"
cp "$D/engine.hpp"          "$P/include/engine.hpp"
cp "$D/render_engine.hpp"   "$P/include/render_engine.hpp"
cp "$D/file_dialog.hpp"     "$P/include/file_dialog.hpp"
cp "$D/ui.hpp"              "$P/include/ui.hpp"
cp "$D/audio_io.hpp"        "$P/include/audio_io.hpp"
cp "$D/ui.cpp"              "$P/src/ui.cpp"
cp "$D/main.cpp"            "$P/src/main.cpp"
cp "$D/audio_io.cpp"        "$P/src/audio_io.cpp"
cp "$D/engine.cpp"          "$P/src/engine.cpp"
cp "$D/render_engine.cpp"   "$P/src/render_engine.cpp"
cp "$D/mod_transport.cpp"   "$P/src/mod_transport.cpp"
cp "$D/mod_magnetic.cpp"    "$P/src/mod_magnetic.cpp"
cp "$D/mod_electronics.cpp" "$P/src/mod_electronics.cpp"
cp "$D/preset_manager.cpp"  "$P/src/preset_manager.cpp"
echo "==> Clean build ..."
rm -rf "$P/build"
cmake -B "$P/build" -G Ninja -DCMAKE_BUILD_TYPE=Release -S "$P"
cmake --build "$P/build" -j"$(nproc)"
echo ""; echo "Done!  Run: $P/build/NagraV"
